### ISSUE TITLE
PPO.loadで学習を再利用できない

### ISSUE THREAD

**Issue by WindVoiceVox** [karaage0703/mario-ai-challenge#3]
途中のPPO.loadで学習済みモデルをロードして追加学習するところ、単にファイル名を指定するだけでは、ロード後model.learn()のときNoneTypeエラーがでて実行できませんでした。

PPO()でmodelを生成するときと、PPO.load()するときでargsを揃えることで追加学習できるようになりました。以下修正案です。

`model = PPO.load('./train/best_model_xxxxx', env, verbose=0, tensorboard_log=LOG_DIR, learning_rate=LEARNING_RATE, n_steps=N_STEPS,
              batch_size=BATCH_SIZE, n_epochs=N_EPOCHS, gamma=GAMMA)`

**Comment by karaage0703** [comment]
@WindVoiceVox 
コメントありがとうございます。
すみません、ロードして追加学習のところは確認していませんでした。

確認して修正いたします。とりあえずお礼まで。

**Comment by karaage0703** [comment]
@WindVoiceVox 
動作確認して、ノートブック修正しました！ご指摘ありがとうございました。
