### ISSUE TITLE
Challenge 8-1

### ISSUE THREAD

**Issue by WindVoiceVox** [karaage0703/mario-ai-challenge#46]
## Stage
8-1

## Status
- [x] Create Notebook
- [x] Clear

## Challenge Notebook Link
[Shared Google Colab Notebook](https://colab.research.google.com/drive/1vVP46sysypcpuAC2_G5EjqLZuqaXQGqZ?usp=sharing)

## Best Movie
[Clear Movie](https://drive.google.com/file/d/181VPp1mH193TR8RhzlBZ7-u68m1kKm-A/view?usp=sharing)

## Best Trained Model
[Trained Model](https://drive.google.com/file/d/1Nf9v4cUk4qa90kGvSTxDhgEx-F37FUzk/view?usp=sharing)

## Challenger
WindVoice ([Twitter](https://twitter.com/WindVoice_jp))

**Comment by WindVoiceVox** [comment]
やっとクリアしましたのでご報告します。動画を用意しました。

https://user-images.githubusercontent.com/15950763/180632432-8df019ce-50e1-4f82-a4a6-df5e2d9ff444.mp4

**Comment by karaage0703** [comment]
@WindVoiceVox 
ありがとうございます！お疲れ様でした。issueは追加しなくて #35 を書き換えて追記すれば大丈夫ですよ。
こちらで書き換えておきました。

ノートブックも奮闘ぶりが感じられます。素晴らしいです。

**Comment by chottokun** [comment]
@WindVoiceVox さん
おめでとうございます！継続学習の問題でマゴマゴしてました。
ノートブックこれからお勉強致します。

さて、私は明日から何をトライしましょう・・・（笑）

**Comment by WindVoiceVox** [comment]
@karaage0703 
#35 でよかったんですね、失礼しました。対処ありがとうございます。
今回のチャレンジは相当いろんなことを学びました。やってよかったです。
冷めてしまわないうちにまとめておかないと。

@chottokun 
ありがとうございます！
PPOを採用するところでNotebook参考にさせていただきました。
ゴールできたのはちょっとの差でした。

8-4は、正直ヤルゾ！って思い立つのがむずかしいですよね。
ステージ確認するとジャンプして空中で→←のコントロールで下の段に降りるとか、正しい土管に入らないとループするとか難易度高すぎです……

**Comment by chottokun** [comment]
@WindVoiceVox 
8-4 は間違いルートはダメと与えないと解けそうにないですよね。それはもやっとしちゃいます。やるべきか。
